In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsRegressor
from sklearn.metrics import mean_absolute_error , r2_score

# K nearest neighbours Algorithm 
    ** momo - f **
    ** thupka - f **
    ** soup - b **
    ** jhol momo - **
    ** chowmein - f **
    ** Coke - b **
    ** Mojito - b **

# Consider k = 5
    ** momo - f **
    ** thupka - f **
    ** Soup - b **
    ** Chowmein - f **
    ** Coke - b **

Here, the majority wins as food (f) is 3 and beverage (b) is 2, So jhol momo is food(f)

In [3]:
from sklearn.datasets import fetch_california_housing

In [4]:
housing_data = fetch_california_housing()


In [5]:
data = pd.DataFrame(housing_data.data , columns =housing_data.feature_names)

In [6]:
data.head()

MedInc  HouseAge  AveRooms  AveBedrms  Population  AveOccup  Latitude  \
0  8.3252      41.0  6.984127   1.023810       322.0  2.555556     37.88   
1  8.3014      21.0  6.238137   0.971880      2401.0  2.109842     37.86   
2  7.2574      52.0  8.288136   1.073446       496.0  2.802260     37.85   
3  5.6431      52.0  5.817352   1.073059       558.0  2.547945     37.85   
4  3.8462      52.0  6.281853   1.081081       565.0  2.181467     37.85   

   Longitude  
0    -122.23  
1    -122.22  
2    -122.24  
3    -122.25  
4    -122.25

In [7]:
data.sample(5)

MedInc  HouseAge  AveRooms  AveBedrms  Population  AveOccup  Latitude  \
1126   2.3403      23.0  4.973626   1.092308      1138.0  2.501099     39.77   
2738   4.6154      35.0  6.204188   1.057592       615.0  3.219895     32.78   
20432  5.4243      25.0  6.390845   0.989437       960.0  3.380282     34.25   
3833   2.5197      35.0  3.468687   0.965657      1628.0  3.288889     34.20   
10066  1.3523      18.0  5.883117   1.519481       152.0  1.974026     39.39   

       Longitude  
1126     -121.60  
2738     -115.56  
20432    -118.74  
3833     -118.44  
10066    -120.74

In [9]:
data['MedHouseVal'] = housing_data.target

In [10]:
data.head()

MedInc  HouseAge  AveRooms  AveBedrms  Population  AveOccup  Latitude  \
0  8.3252      41.0  6.984127   1.023810       322.0  2.555556     37.88   
1  8.3014      21.0  6.238137   0.971880      2401.0  2.109842     37.86   
2  7.2574      52.0  8.288136   1.073446       496.0  2.802260     37.85   
3  5.6431      52.0  5.817352   1.073059       558.0  2.547945     37.85   
4  3.8462      52.0  6.281853   1.081081       565.0  2.181467     37.85   

   Longitude  MedHouseVal  
0    -122.23        4.526  
1    -122.22        3.585  
2    -122.24        3.521  
3    -122.25        3.413  
4    -122.25        3.422

In [11]:
import joblib

In [12]:
y = data['MedHouseVal']
X = data.drop(['MedHouseVal' ], axis = 1)

In [13]:
X_train , X_test , y_train , y_test = train_test_split(X , y ,
                                                       test_size= 0.2 , 
                                                       random_state = 999
                                                      )

In [14]:
from sklearn.preprocessing import StandardScaler

In [15]:
scaler = StandardScaler()

In [16]:
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [17]:
X_train[0]

array([ 0.02598178,  0.42423372, -0.05252651,  0.05826392, -0.42478176,
        0.00086802, -0.66679549,  0.52939746])

In [18]:
X_test[0]

array([-0.07398232, -1.72018651,  0.10952152, -0.19010449, -0.39351486,
        0.00904356,  0.50609026, -0.00607151])

In [19]:
knn = KNeighborsRegressor(n_neighbors = 7 , n_jobs=-1)

In [20]:
knn.fit(X_train , y_train)

KNeighborsRegressor(n_jobs=-1, n_neighbors=7)

In [21]:
y_pred = knn.predict(X_test)

In [22]:
r2_score(y_test , y_pred)

0.6993831587062577

In [23]:
mean_absolute_error(y_test , y_pred)

0.44557939680232556

In [24]:
joblib.dump(scaler , 'Standard_Scaler.pkl')

['Standard_Scaler.pkl']

In [25]:
joblib.dump(knn , 'KNN_California_Housing.pkl')

['KNN_California_Housing.pkl']

In [26]:
data.sample(5).values

array([[ 1.57390000e+00,  1.60000000e+01,  5.91457286e+00,
         1.20603015e+00,  5.19000000e+02,  2.60804020e+00,
         3.88700000e+01, -1.22640000e+02,  7.35000000e-01],
       [ 3.06700000e+00,  2.80000000e+01,  3.96666667e+00,
         1.09523810e+00,  3.49000000e+02,  1.66190476e+00,
         3.40800000e+01, -1.18390000e+02,  3.75000000e+00],
       [ 2.12500000e+00,  5.00000000e+01,  4.24242424e+00,
         1.07196970e+00,  6.97000000e+02,  2.64015152e+00,
         3.78500000e+01, -1.22260000e+02,  1.40000000e+00],
       [ 3.96130000e+00,  3.50000000e+01,  5.17312661e+00,
         9.76744186e-01,  1.72600000e+03,  4.45994832e+00,
         3.37700000e+01, -1.17900000e+02,  1.82300000e+00],
       [ 6.22750000e+00,  3.40000000e+01,  6.21530249e+00,
         9.75088968e-01,  2.86500000e+03,  2.54893238e+00,
         3.78800000e+01, -1.22140000e+02,  3.94400000e+00]])