In [1]:
import numpy as np
import pandas as pd

In [2]:
np.__version__

'1.24.3'

In [3]:
pd.__version__


'1.5.3'

# NUMPY BASICS

In [4]:
a_list = [1 , 2 , 3 , 4 , 5 , 6 , 7 , 8 , 9 , 10]
a_list

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [7]:
type(a_list)

list

In [8]:
a_arr = np.array(a_list)

In [9]:
type(a_arr)

numpy.ndarray

In [10]:
len(a_list)

10

In [13]:
a_arr.shape

(10,)

In [16]:
a_arr.reshape(5 , 2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [17]:
a_arr.reshape(2 , 5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [19]:
a_arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [26]:
a_arr = a_arr.reshape(5 , 2)

In [27]:
a_arr

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [28]:
a_arr[0]

array([1, 2])

In [30]:
a_arr.shape

(5, 2)

In [31]:
a_arr.T # Transposing the matrix

array([[ 1,  3,  5,  7,  9],
       [ 2,  4,  6,  8, 10]])

In [32]:
np.arange(100) #Numpy way of generating numbers, similar to range( ) in python

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [34]:
a = np.arange(100 , 300 , 2)
a

array([100, 102, 104, 106, 108, 110, 112, 114, 116, 118, 120, 122, 124,
       126, 128, 130, 132, 134, 136, 138, 140, 142, 144, 146, 148, 150,
       152, 154, 156, 158, 160, 162, 164, 166, 168, 170, 172, 174, 176,
       178, 180, 182, 184, 186, 188, 190, 192, 194, 196, 198, 200, 202,
       204, 206, 208, 210, 212, 214, 216, 218, 220, 222, 224, 226, 228,
       230, 232, 234, 236, 238, 240, 242, 244, 246, 248, 250, 252, 254,
       256, 258, 260, 262, 264, 266, 268, 270, 272, 274, 276, 278, 280,
       282, 284, 286, 288, 290, 292, 294, 296, 298])

In [35]:
a.shape

(100,)

In [36]:
a_list

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [46]:
#adding some number to every element in list
for x , list_element  in enumerate(a_list):
    #print(x)
    a_list[x] +=4

In [47]:
a_list

[5, 6, 7, 8, 9, 10, 11, 12, 13, 14]

In [48]:
a +=18

In [49]:
a

array([118, 120, 122, 124, 126, 128, 130, 132, 134, 136, 138, 140, 142,
       144, 146, 148, 150, 152, 154, 156, 158, 160, 162, 164, 166, 168,
       170, 172, 174, 176, 178, 180, 182, 184, 186, 188, 190, 192, 194,
       196, 198, 200, 202, 204, 206, 208, 210, 212, 214, 216, 218, 220,
       222, 224, 226, 228, 230, 232, 234, 236, 238, 240, 242, 244, 246,
       248, 250, 252, 254, 256, 258, 260, 262, 264, 266, 268, 270, 272,
       274, 276, 278, 280, 282, 284, 286, 288, 290, 292, 294, 296, 298,
       300, 302, 304, 306, 308, 310, 312, 314, 316])

In [66]:
a -=18

In [67]:
a

array([100, 102, 104, 106, 108, 110, 112, 114, 116, 118, 120, 122, 124,
       126, 128, 130, 132, 134, 136, 138, 140, 142, 144, 146, 148, 150,
       152, 154, 156, 158, 160, 162, 164, 166, 168, 170, 172, 174, 176,
       178, 180, 182, 184, 186, 188, 190, 192, 194, 196, 198, 200, 202,
       204, 206, 208, 210, 212, 214, 216, 218, 220, 222, 224, 226, 228,
       230, 232, 234, 236, 238, 240, 242, 244, 246, 248, 250, 252, 254,
       256, 258, 260, 262, 264, 266, 268, 270, 272, 274, 276, 278, 280,
       282, 284, 286, 288, 290, 292, 294, 296, 298])

In [70]:
a * 2

array([200, 204, 208, 212, 216, 220, 224, 228, 232, 236, 240, 244, 248,
       252, 256, 260, 264, 268, 272, 276, 280, 284, 288, 292, 296, 300,
       304, 308, 312, 316, 320, 324, 328, 332, 336, 340, 344, 348, 352,
       356, 360, 364, 368, 372, 376, 380, 384, 388, 392, 396, 400, 404,
       408, 412, 416, 420, 424, 428, 432, 436, 440, 444, 448, 452, 456,
       460, 464, 468, 472, 476, 480, 484, 488, 492, 496, 500, 504, 508,
       512, 516, 520, 524, 528, 532, 536, 540, 544, 548, 552, 556, 560,
       564, 568, 572, 576, 580, 584, 588, 592, 596])

In [71]:
a.shape

(100,)

In [76]:
a = a.reshape(10 , 10)

In [77]:
b = np.arange(100).reshape(10 , 10)

In [78]:
b

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [79]:
a + b

array([[100, 103, 106, 109, 112, 115, 118, 121, 124, 127],
       [130, 133, 136, 139, 142, 145, 148, 151, 154, 157],
       [160, 163, 166, 169, 172, 175, 178, 181, 184, 187],
       [190, 193, 196, 199, 202, 205, 208, 211, 214, 217],
       [220, 223, 226, 229, 232, 235, 238, 241, 244, 247],
       [250, 253, 256, 259, 262, 265, 268, 271, 274, 277],
       [280, 283, 286, 289, 292, 295, 298, 301, 304, 307],
       [310, 313, 316, 319, 322, 325, 328, 331, 334, 337],
       [340, 343, 346, 349, 352, 355, 358, 361, 364, 367],
       [370, 373, 376, 379, 382, 385, 388, 391, 394, 397]])

In [80]:
a.mean()

199.0

In [81]:
a.max()

298

In [82]:
a.min()

100

In [83]:
a.std()

57.73214009544424

In [84]:
#Row wise mean
a.mean(axis = 1)

array([109., 129., 149., 169., 189., 209., 229., 249., 269., 289.])

In [85]:
#Column wise mean
a.mean(axis = 0)

array([190., 192., 194., 196., 198., 200., 202., 204., 206., 208.])

In [86]:
a

array([[100, 102, 104, 106, 108, 110, 112, 114, 116, 118],
       [120, 122, 124, 126, 128, 130, 132, 134, 136, 138],
       [140, 142, 144, 146, 148, 150, 152, 154, 156, 158],
       [160, 162, 164, 166, 168, 170, 172, 174, 176, 178],
       [180, 182, 184, 186, 188, 190, 192, 194, 196, 198],
       [200, 202, 204, 206, 208, 210, 212, 214, 216, 218],
       [220, 222, 224, 226, 228, 230, 232, 234, 236, 238],
       [240, 242, 244, 246, 248, 250, 252, 254, 256, 258],
       [260, 262, 264, 266, 268, 270, 272, 274, 276, 278],
       [280, 282, 284, 286, 288, 290, 292, 294, 296, 298]])

In [87]:
#Row wise standard deviation
a.std(axis = 1)

array([5.74456265, 5.74456265, 5.74456265, 5.74456265, 5.74456265,
       5.74456265, 5.74456265, 5.74456265, 5.74456265, 5.74456265])

In [88]:
#Column wise standard deviation
a.std(axis = 0)

array([57.44562647, 57.44562647, 57.44562647, 57.44562647, 57.44562647,
       57.44562647, 57.44562647, 57.44562647, 57.44562647, 57.44562647])

In [92]:
np.arange(1 ,10 ,0.2)

array([1. , 1.2, 1.4, 1.6, 1.8, 2. , 2.2, 2.4, 2.6, 2.8, 3. , 3.2, 3.4,
       3.6, 3.8, 4. , 4.2, 4.4, 4.6, 4.8, 5. , 5.2, 5.4, 5.6, 5.8, 6. ,
       6.2, 6.4, 6.6, 6.8, 7. , 7.2, 7.4, 7.6, 7.8, 8. , 8.2, 8.4, 8.6,
       8.8, 9. , 9.2, 9.4, 9.6, 9.8])

In [93]:
np.arange(1 ,10 ,0.2).shape

(45,)

In [94]:
np.linspace(1 , 10 ,50) #linspace(start , stop , size)

array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])

In [95]:
np.linspace(1 , 10 ,50 , dtype = int) 

array([ 1,  1,  1,  1,  1,  1,  2,  2,  2,  2,  2,  3,  3,  3,  3,  3,  3,
        4,  4,  4,  4,  4,  5,  5,  5,  5,  5,  5,  6,  6,  6,  6,  6,  7,
        7,  7,  7,  7,  7,  8,  8,  8,  8,  8,  9,  9,  9,  9,  9, 10])

In [96]:
one = np.ones(100)
one.reshape(10 , 10)

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [98]:
zero = np.zeros(100)
zero.reshape(10 , 10)

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [100]:
twenty_fives = zero + 25
twenty_fives

array([25., 25., 25., 25., 25., 25., 25., 25., 25., 25., 25., 25., 25.,
       25., 25., 25., 25., 25., 25., 25., 25., 25., 25., 25., 25., 25.,
       25., 25., 25., 25., 25., 25., 25., 25., 25., 25., 25., 25., 25.,
       25., 25., 25., 25., 25., 25., 25., 25., 25., 25., 25., 25., 25.,
       25., 25., 25., 25., 25., 25., 25., 25., 25., 25., 25., 25., 25.,
       25., 25., 25., 25., 25., 25., 25., 25., 25., 25., 25., 25., 25.,
       25., 25., 25., 25., 25., 25., 25., 25., 25., 25., 25., 25., 25.,
       25., 25., 25., 25., 25., 25., 25., 25., 25.])

In [104]:
np.linspace(25 , 25 ,100 , dtype=int)

array([25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25,
       25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25,
       25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25,
       25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25,
       25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25,
       25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25])

In [107]:
np.identity(5 , dtype=int)

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [108]:
np.identity(5 , dtype=int) * 18

array([[18,  0,  0,  0,  0],
       [ 0, 18,  0,  0,  0],
       [ 0,  0, 18,  0,  0],
       [ 0,  0,  0, 18,  0],
       [ 0,  0,  0,  0, 18]])

In [109]:
np.eye(5 , 5 , dtype=int)

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [110]:
np.eye(5 , 8 , dtype = int)

array([[1, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0]])

In [111]:
arr = np.arange(1 , 13)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [113]:
arr = arr.reshape(3 , 4)
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [115]:
arr2 = np.arange(1 , 13).reshape(4 ,3)

In [116]:
arr * arr2.T
#element wise multiplication

array([[  1,   8,  21,  40],
       [ 10,  30,  56,  88],
       [ 27,  60,  99, 144]])

In [117]:
np.dot(arr ,arr2) #matrix multiplication

array([[ 70,  80,  90],
       [158, 184, 210],
       [246, 288, 330]])